name: docker-bake-gha-cache

on:
  push: {}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Bake
        uses: docker/bake-action@v2.2.0
        with:
          pull: true
          push: ${{ github.reb == 'refs/heads/main' }}
          files: docker-bake-gha-cache/docker-bake.hcl
